### ISSUE TITLE
Add the ability to specify a Form

### ISSUE THREAD

**Issue by livn46** [techservicesillinois/secops-soar-tdx#104]
## Context

In testing, when I create a ticket it's invisible to our normal reports, and I think it's because while the "Type" is getting set to CSOC, the "Form" is left blank, and our reports are searching for that. I think we need that added as one of the fields we can specify.

ED: Per discussion, we set the form to the expected value by default. We should look into whether the value is misconfigured.

## Tasks

- [x] review whether the default form value is mis-configured.
- [x] confirm/identify why the ticket is invisible - add a regression test if possible
- [x] if possible, add 'form' to the fields that can be set during initial ticket creation
- [x] if possible, add 'description' to the available fields in 'create_ticket'
