### ISSUE TITLE
able to assign tdx ticket to someone right off the bat... 

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#105]
## Context

It would also be nice to be able to assign it to someone right off the bat... did we already discuss that and decide that it was not possible for some reason? I think I remember asking about this once before. I also think I remember asking about the Description field: without a description field, only a Title field, the ticket is rather sparse.

NOTE: We added 'description' handling  to #104, since it will fit better with that work/code.

_Originally posted by @livn46 in https://github.com/techservicesillinois/secops-soar-tdx/issues/104#issuecomment-1991818533_

Fine to have this as a dedicated block that requires an assignee, and then calls the other two handlers in order.

## Tasks

- [x] analyze adding a 'create_ticket_and_assign_to_user' block
- [ ] create `_handle_create_ticket_assign_to_user` handler (can use same params as `handle_create_ticket` handler. Advise users to put NetId of desired assignee in the `responsible` field)
  - [ ] call the `_handle_create_ticket` handler from new handler using a default group (we can probably use "UIUC-TechServices-Cybersecurity Incident Response")
  - [ ] get the ticket number from the response
  - [ ] call the `reassign_user` handler, passing it the ticket number and NetId of the desired assignee

**Comment by edthedev** [comment]
This update will likely pair well with #137.

**Comment by zdc217** [comment]
Creating a ticket and assigning to a user immediately is not supported by the TDX API. 

We may be able pull it off by combining a couple of calls but in practice it would result in code that's confusing and tough to maintain, since we would have to juggle a bunch of defaults and then change some of them to the correct values in a subsequent call.
