### ISSUE TITLE
Add ability to set `description` field on `create` and on `update`

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#109]
## Context

@livn46 is prototyping and needs to be able to add information into the `description` field

## Tasks

- [ ] add some unit tests around the `create` handler
- [ ] update `app.json` with support for passing in `description` to `create`
- [ ] update `app.json` with support for passing in `description` to `update`
- [ ] update the `create` handler
- [ ] update the `update` handler
