### ISSUE TITLE
Error when calling `create` with `notify` unchecked

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#110]
## Steps to Reproduce

- Use the `create` action, but leave `notify` unchecked

## Trace

```
'create_ticket_in_tdx_1' on asset 'tdx sandbox': 2 actions failed. (1)For Parameter: {"TLP":"Amber","context":{"artifact_id":434589,"guid":"4edbc29c-4920-4bcd-8171-0d8ca3857cc6","parent_action_run":[]},"description":"The machine at 10.251.130.92 is communicating with -\n113.206.29.10 at 113.206.29.10 on Destination Port 17107, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.19 at 123.184.152.19 on Destination Port 18251, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.20 at 123.184.152.20 on Destination Port 18465, which is unique to this machine.","formid":"UIUC-TechSvc-CSOC Incidents","priority":"Low","requestor":"security@illinois.edu","responsible":"UIUC-TechServices-Cybersecurity Incident Response","severity":"To Be Determined","title":"Enterprise Security Notable - 10.251.130.92","type":"CSOC"} Message: "". (2)For Parameter: {"TLP":"Amber","context":{"artifact_id":434589,"guid":"4edbc29c-4920-4bcd-8171-0d8ca3857cc6","parent_action_run":[]},"description":"The machine at 10.251.130.92 is communicating with -\n113.206.29.10 at 113.206.29.10 on Destination Port 17107, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.19 at 123.184.152.19 on Destination Port 18251, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.20 at 123.184.152.20 on Destination Port 18465, which is unique to this machine.","formid":"UIUC-TechSvc-CSOC Incidents","priority":"Low","requestor":"security@illinois.edu","responsible":"UIUC-TechServices-Cybersecurity Incident Response","severity":"To Be Determined","title":"Enterprise Security Notable - 10.251.130.92","type":"CSOC"} Message: "handle_action exception occurred. Error string: ''notify''"
Jul 31, 14:33:08 : 'create_ticket_in_tdx_1'  on asset 'tdx sandbox' completed with status: 'failed'. Action Info: Size : 1.92 KB : [{"app_name":"Test Team Dynamix","asset_name":"tdx sandbox","param":{"TLP": "Amber", "type": "CSOC", "title": "Enterprise Security Notable - 10.251.130.92", "formid": "UIUC-TechSvc-CSOC Incidents", "context": {"guid": "4edbc29c-4920-4bcd-8171-0d8ca3857cc6", "artifact_id": 434589, "parent_action_run": []}, "priority": "Low", "severity": "To Be Determined", "requestor": "security@illinois.edu", "description": "The machine at 10.251.130.92 is communicating with -\n113.206.29.10 at 113.206.29.10 on Destination Port 17107, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.19 at 123.184.152.19 on Destination Port 18251, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.20 at 123.184.152.20 on Destination Port 18465, which is unique to this machine.", "responsible": "UIUC-TechServices-Cybersecurity Incident Response"},"status":"failed","message":""},{"app_name":"Test Team Dynamix","asset_name":"tdx sandbox","param":{"TLP": "Amber", "type": "CSOC", "title": "Enterprise Security Notable - 10.251.130.92", "formid": "UIUC-TechSvc-CSOC Incidents", "context": {"guid": "4edbc29c-4920-4bcd-8171-0d8ca3857cc6", "artifact_id": 434589, "parent_action_run": []}, "priority": "Low", "severity": "To Be Determined", "requestor": "security@illinois.edu", "description": "The machine at 10.251.130.92 is communicating with -\n113.206.29.10 at 113.206.29.10 on Destination Port 17107, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.19 at 123.184.152.19 on Destination Port 18251, which is unique to this machine.,The machine at 10.251.130.92 is communicating with -\n123.184.152.20 at 123.184.152.20 on Destination Port 18465, which is unique to this machine.", "responsible": "UIUC-TechServices-Cybersecurity Incident Response"},"status":"failed","message":"handle_action exception occurred. Error string: ''notify''"}]
```
Specific error:
```
Message: "handle_action exception occurred. Error string: ''notify''"
```

## Tasks

- [ ] duplicate the issue
- [x] check whether the field is required in `app.json`.  https://github.com/techservicesillinois/secops-soar-tdx/blob/1d0f4e36bb50fe5ca5628216540ba2e85bd39f79/src/app/app.json#L160C21-L160C39
- [ ] trace the exception handler process
- [ ] create a test that sends various invalid versions of `notify=false` into the `create` handler. Send zero, empty string, etc. to try to replicate
