### ISSUE TITLE
Upgrade to use `phantom-toolbox`.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#113]
## Context

- `deploy.py` is duplicated across repositories, including this one.
- `NiceBaseConnector` is available in `phantom-toolbox` and removes a substantial amount of duplicated code in `app.py`.

See `app.py`, `Makefile` and `requirements` files in https://github.com/techservicesillinois/soar-clearpass for examples.

## Tasks

- [x] add `phantom toolbox` to the `app.json` requirements section
- [x] add `phantom-toolbox` to `requirements` files and `Makefile` (copy example lines from `soar-clearpass`)
- [x] update `Makefile` to use `phantom-toolbox` in the `deploy` step
- [x] remove `deploy.py`

Continued in #115
