### ISSUE TITLE
find and remove any hard-coded translation tables that are unique to our environment

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#121]
## Context

We have 14 additional values that are specific to our environment.

https://github.com/techservicesillinois/secops-soar-tdx/blob/439f64c0021dde1de46a04ca4dbb6094ef888894/src/app/app.py#L25-L46

## Tasks

- [ ] Add 14 new configuration value options
- [ ] Set all 14 defaults to our instances values
- [ ] Ideally, document how to find the field IDs in the TDX web interface
- [ ] Update our code in `initialize` to use the configured values
