### ISSUE TITLE
Add configuration settings

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#13]
## Context

Various TDX configuration elements are currently hard-coded.

```python
        self.account_name = "None/Not found" # TODO: pull from config

        # TODO: Most of this config should be available in SOAR settings.
        self.tdx = tdxlib.tdx_ticket_integration.TDXTicketIntegration(config={ 
            'TDX API Settings': {
                "orgname": "myuniversity",
                "fullhost": "help.uillinois.edu",
                "sandbox": True,
                "username": config.get('TDX_USERNAME'),
                "password": config.get('TDX_PASSWORD'),
                "ticketAppId": 66,
                "assetAppId": "",
                "caching": False,
                "timezone": "-0500",
                "logLevel": "ERROR",
        }})
```

## Tasks

- [ ] add config settings
- [ ] update tdx_connector.py settings to use new values
- [ ] username and password should become settings, rather than env variables
- [ ] update account name used in conftest.py to also use the config or a hard-coded setting
- [ ] double-check that test suite still works with username and password from ENV
