### ISSUE TITLE
Verify that app.tar is uploaded on `pre-release`, while not published to our SOAR instance, yet.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#130]
## Context

We want to create a `2.2.0` release for manual testing (download tar file), but doing so currently will publish to our Splunk instance.

## Tasks

- [x] add github.event.action != 'prereleased' to the deploy step checks (#129)
- [x] create a pre-release
- [ ] verify that the app version is not published on pre-release
- [ ] verify that a copy of the app is uploaded to the 'assets' section of the pre-release
- [ ] if needed - due to accidental release - revert the app to 2.1.0 in the SOAR web interface.
- [ ] reach out to CSOC to coordinate doing the official release and update, when ready

**Comment by edthedev** [comment]
This has been fighting us. Cannot get `pre-release` to correctly trigger a GitHub Action run. 
We may pivot to #134, so we can more promptly verify the rest of the functionality.

**Comment by edthedev** [comment]
Blocked by #134
