### ISSUE TITLE
Restore unmodified deploy.yml after template includes release asset tar file

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#132]
## Context

We have modified `deploy.yml` with an update to add `app.tar` to our release assets - to make it easier for collaborators to find and download for use in their own Splunk SOAR environments.

But we prefer that `deploy.yml` match between each of our projects, so we have opened
https://github.com/techservicesillinois/splunk-soar-template/issues/73 to backport this change after we are done tuning it, into our template repository.

Once https://github.com/techservicesillinois/splunk-soar-template/issues/73 is completed, we should restore our `deploy.yml` to be an exact copy of the template version.

## Tasks

- [ ] blocked by https://github.com/techservicesillinois/splunk-soar-template/issues/73
- [ ] copy `deploy.yml` from `splunk-soar-template` here
- [ ] re-verify asset release/pre-release functionality

**Comment by edthedev** [comment]
This is no longer valid, pending outcome of discussion in https://github.com/techservicesillinois/secops-soar-tdx/issues/134 - we will plan next steps after, and open new issues.
