### ISSUE TITLE
Re-work release process to support both `deploy.py` (for ourselves) and `app.tar` (for our collaborators).

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#134]
## Context

              This work is done, but we haven't been able to get `pre-release` to trigger a GitHub action workflow. I'm inclined to just make this a manual workflow.

_Originally posted by @edthedev in https://github.com/techservicesillinois/secops-soar-tdx/issues/118#issuecomment-2532900552_

Unable to test our `app.tar` asset upload to release, because GitHub actions does not behave as expected, on a pre-release.

Would love to separate verifying this change, from gaining a comprehensive understanding of 'pre-release', since `pre-release` was just meant to be a quick way to test. 

It feels like a manual workflow is part of the solution, but which workflow steps to separate, and how big of a change to make, is an open question, since our release documentation and training and process will be impacted. It will also no longer match our other release workflows.
            
## Tasks

- [ ] discuss changes to our release workflow to support uploading an `app.tar` asset to the release area.
- [ ] discuss other possible release areas
- [ ] discuss manual work-flows as work-arounds
- [ ] decide a direction
- [ ] open a new issue to implement

**Comment by edthedev** [comment]
We will also want it to trigger on all releases, but with a separate manual way to invoke it, we could at least verify that the package arrives as desired.

**Comment by edthedev** [comment]
Let's also discuss this in the context that we probably want to adjust our release process for our other three (soon four) apps to match.
