### ISSUE TITLE
Remove all TODO tasks related to using our fork once we're able to use the PyPI version

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#14]
## Tasks

- [ ] update our requirements to use the PyPI version (or at least clone from public GitHub repo) of pytest-splunk-soar
- [ ] re-run the test suite
- [ ] make the same updates to our soar-template repo.
