### ISSUE TITLE
Deployment WTF

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#16]
## Tasks

- [ ] look again with fresh eyes at requirements.in and app.json
- [ ] look in previous .json file and notes - add additional json attributes that tell Splunk SOAR that "we mean it" about deploying from API
- [ ] try pushing everything to lower case - TDX vs tdx? 
- [ ] delete the app entirely on our SOAR instance and then re-deploy
- [ ] ask SecEng to look in additional admin options?
- [ ] rebase to 1 commit and open source this repository so that Daniel can read along
- [ ] email Daniel with error message
