### ISSUE TITLE
Resolve open test suite issues in TDX SOAR app

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#2]
## Context

Test suite is not passing on main, due to cassette playback not completing during connectivity test.

## Tasks

- [x] update cassette decorator to match other projects
- [x] review cassette and calling code for conflicts
- [x] get TDX API credentials reset
- [x] [re-reset TDX API credentials to eliminate problem characters][1] (`%, ', \, "`) (TDX ticket updated, reset in progress as of Monday 11/28)
- [x] re-record the existing cassettes
- [x] if necessary, update cassettes or test_connectivity code   

[1]: https://help.uillinois.edu/TDNext/Apps/40/Tickets/TicketDet.aspx?TicketID=553859
