### ISSUE TITLE
TDX SOAR app Demo to CSOC and Engineering

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#21]
## Tasks

- [x] decide a demo team 
- [x] reach out to Glen to get on the CSOC Automation meeting agenda
- [x] do the demo
