### ISSUE TITLE
Re-pin TdxLib

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#24]
## Context

We had to to un-pin our upstream version of TDXlib in the Splunk SOAR app.json settings file, because `==2.4.0` is not supported in the `"pip3_dependencies": {
        "pypi": [` block.

  Can we pin this in another way? Maybe the dict supports a `version` key?

_Originally posted by @ddriddle in https://github.com/techservicesillinois/secops-soar-tdx/pull/23#discussion_r1047430939_

## Tasks

- [x] review available Splunk SOAR docs for another obvious option
- [x] reach out to our Splunk team to pass along the question - is there a way to pin our library versions in Splunk SOAR cloud?
- [x] update deployment to deploy TDXLib via the .wheel method that we use for soar-null-router.
