### ISSUE TITLE
Replace our cleaner libraries with functions from scrub-a-dub

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#29]
Context - we clean email address and phone numbers out of data returned from TDX and logged to VCRpy with custom code right now. It seems likely we could reduce our code by adding Scrub-a-dub to this process.

https://scrubadub.readthedocs.io/en/stable/

## Tasks

- [ ] explore scrub-a-dub functions 
- [ ] decide whether to integrate scrub-a-dub into our response cleaner to simplify it
- [ ] integrate scrub-a-dub into our response cleaner to simplify it
- [ ] evaluate if the response cleaner should be moved upstream into vcrpy-cleaner, and open new issues if so
