### ISSUE TITLE
test_create_ticket cassette is huge and has PII in it

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/secops-soar-tdx#3]
The test_create_ticket.yaml cassette that VCRpy is generating:

a) Is very large - we may want to consider using a different ticket
b) Contains PII - I saw Tam's email address a bunch of times. We should scrub the response a bit.

## Tasks

- [x] fix the over-zealous token scubber
- [x] scrub the response body for PII
- [x] restore the code that scrubs the bearer token
