### ISSUE TITLE
Apply deployment fix

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#30]
See [template repo](https://github.com/techservicesillinois/splunk-soar-template/pull/19/files) for details.

## Tasks

- [x] apply a missing update to the template - https://github.com/techservicesillinois/splunk-soar-template/issues/36
- [x] apply changes to CI/CD `.yaml` file
- [x] apply changes to Makefile
- [x] apply changes to `app.json` file
- [x] add `config.mk` file
- [x] deploy.py
