### ISSUE TITLE
Add 'assign' block that assigns a TDX ticket to a user

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#32]
## Context

Planned incident response automations will require the ability to use the 'assign' action in TDX from SOAR.

## Tasks

- [x] explore the TDX lib assign functionality - see the [reassign function](https://github.com/cedarville-university/tdxlib/blob/master/tdxlib/tdx_ticket_integration.py#L304) in tdx_ticket_integration 
- [x] add failing test for 'reassign' action
- [x] resolve user/group search permissions
- [x] update code to pass the test (reassign group)
- [x] verify the cassette recording (reassign group)
- [x] update JSON to reveal the new 'reassign_group' action
- [ ] update JSON to reveal the new 'reassign_user' action
- [ ] add a reassign user test
- [ ] explore failure cases (expected errors) known by TDX lib when using an action
- [ ] add unhappy path tests for known failure cases 
- [ ] deploy to SOAR test app and test on SOAR
