### ISSUE TITLE
Fix 'required config keys ... not specified' errors.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#33]
## Context

[3:56 PM] Heren, Bob
    FYI, I just tried out the TDX app with the tdx_sandbox asset selected, and it failed: the debug screen printed out this error:

Apr 05, 15:52:53 : 1 action succeeded

Apr 05, 15:52:54 : 'create_ticket_1' on asset 'tdx_sandbox': Loaded action execution configuration

Apr 05, 15:52:59 : 'create_ticket_1' on asset 'tdx_sandbox': Required config keys 'loglevel, orgname' not specified.

Apr 05, 15:52:59 : 'create_ticket_1' on asset 'tdx_sandbox' completed with status: 'failed'. Message: ''create_ticket_1' on asset 'tdx_sandbox': Required config keys 'loglevel, orgname' not specified.'

​[3:56 PM] Heren, Bob
    I did fill out all the fields visible in SOAR, but it looks like it was expecting some additional ones.
(1 liked)<https://teams.microsoft.com/l/message/19:9bffddcde9924ba7ad2d45b394052b45@thread.skype/1680728180413?tenantId=44467e6f-462c-4ea2-823f-7800de5434e3&amp;groupId=293d6f51-9166-4f6f-b6cd-f3335c630c02&amp;parentMessageId=1680728180413&amp;teamName=PrivSec&amp;channelName=SecDevOps&amp;createdTime=1680728180413&amp;allowXTenantAccess=false>

## Tasks

- [x] review how loglevel and orgname are set (or left unset)
- [ ] add tests that confirm loglevel and orgname are handled in some form
- [x] likely: expose loglevel and orgname as configuration attributes in the SOAR app
