### ISSUE TITLE
Prep for open source release

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#35]
## Context

The TDX API tends to return the full name and email address of whoever is using it, and we record that network traffic into YAML files in GitHub to replay it while testing this app.

While these aren't incredibly sensitive, we kept this app `private` while we worked out how to reliably clean that information out of the network recording, as a courtesy to our team members.

That said, our network recording cleaner (vcr_cleaner Python library) is reliable now. 

Again, as a courtesy, we should squash older commits before we publish. 
But I think we are ready to share this source code, after that.

## Tasks

- [x] review our open-source checklist 
- [x] add our standard LICENSE, security.md, contributing, code of conduct files.
- [x] add end-of-life language to the top of CHANGELOG
- [x] make sure that key features from `git log` are documented in CHANGELOG
- [x] squash the commit history to eliminate older versions of the YAML network traffic recordings
- [x] unprotect the main branch
- [x] force push the squashed history to `main`
- [x] delete all other branches
- [x] review the cassette files for any concerns
- [x] #124
- [x] #123
 - [x] #120
 - [x] #121
- [x] #122
