### ISSUE TITLE
Add a `make` target for requirements.txt

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#49]
## Tasks

- [ ] generate and version control a requirements.txt file
- [ ] Make sure requirements.txt includes libraries from both requirements.in
- [ ] Update `venv` target to only rely on requirements.txt
