### ISSUE TITLE
Return newly created ticket number from create_ticket

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#5]
## Context

When the `create_ticket` block is called, the new ticket number should be returned for Splunk SOAR playbooks to use.

## Tasks

- [x] JSON update
- [x] code update
- [x] add needed secrets to GitHub Secrets Actions
- [x] deploy to SOAR (failing  - https://github.com/techservicesillinois/secops-soar-tdx/actions/runs/3631565223/jobs/6126412378)
- [x] verify ticket id returns in SOAR
