### ISSUE TITLE
Verify GIT_TAG and GIT_HASH make it into the source code

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#7]
## Context

I note that we currently point to `__init__.py` and we had issues on SOAR when trying to import the variables from `__init__.py`. We solved this in other projects by moving those to variables into the main Python code file.

## Tasks

- [ ] move the git variables out of __init__.py
- [ ] update the Makefile git hash and tag handling, replacing __init__.py with the new filename  
- [ ] verify that `make version` updates the variables in the main Python code file
- [ ] verify that `make version` updates the main `.json` file with the current tag number or 0.0.0
- [ ] be sure not to check in the results of `make version` since we only want that to happen right before deployment
