### ISSUE TITLE
Type and Status should have a default and not need a selection on ticket creation

### ISSUE THREAD

**Issue by baristaTam** [techservicesillinois/secops-soar-tdx#74]
Should we do this? Or is it overly specific? Ideally for CSOC ease of use, Type should always be CSOC and Status should always be New on ticket creation. These don't need to be editable from SOAR.

## Tasks

- [x] Discuss with Ed if this should be done or not
- ~~Remove Status and Type from app.json~~
- [x] add the default values to app.json
- [x] add a test that verifies that create_ticket can be called without providing those values
