### ISSUE TITLE
Add a test that appropriate SOAR messaging happens when a call to TDX results in a 408 or 500 error

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#8]
## Context

Things won't always work. `408 - Timeout` and `500 - TDX Is Broken Right Now` are both statuses that we would rather see great messaging in Splunk SOAR, than to have to manually diagnose. Let's add a couple of tests to ensure a clear message is emitted in these cases.

## Tasks

- [x] send garbage to TDX
- [x] record response
- [x] assert good message 
- [x] handle known tdxlib errors
