### ISSUE TITLE
Add deployed .tgz file to Release assets

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#83]
## Context

UIC would like to start using this app.

The current .tgz file attached to each Release is just a source tarball. We want to attach the actual .tgz that we build and deploy to SOAR through the API.

## Tasks

- [x] add read access for Carl's GitHub account, so he can download the .tgz releases
- [x] add a link from README to any docs that Splunk has about doing a .tgz install / upload
- [x] make sure the tdx soar app publishes the deployed.tgz as an asset to the release area
- [ ] send link to release page to Carl
