### ISSUE TITLE
Add update block

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#87]
## Context

We have a `create ticket` method, but no `update ticket` method yet.

## Tasks

- [ ] add `update` the the available methods defined in `app.json`
- [ ] add tests for `handle_update`
- [ ] code `handle_update`
